---
version: '2'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.1
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    broker-1:
        image: confluentinc/cp-server:7.6.1
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_LISTENERS: INTERNAL://broker-1:29092,EXTERNAL://:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:29092,EXTERNAL://localhost:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    broker-2:
        image: confluentinc/cp-server:7.6.1
        depends_on:
            - zookeeper
        ports:
            - "9093:9092"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_LISTENERS: INTERNAL://broker-2:29092,EXTERNAL://:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:29092,EXTERNAL://localhost:9093
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL


    broker-3:
        image: confluentinc/cp-server:7.6.1
        depends_on:
            - zookeeper
        ports:
            - "9094:9092"
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_LISTENERS: INTERNAL://broker-3:29092,EXTERNAL://:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-3:29092,EXTERNAL://localhost:9094
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL